# Zugangsdaten Mirakel-Datenbank:
MIRAKEL:
    db_name: 
    db_port: 
    db_user: 
    db_pwd: 
    db_hostname: 
    db_hostname_alt: 
    db_service: 
    db_arraysize: 1000
    db_connection_string_raw: > 
        (DESCRIPTION =
        (ADDRESS_LIST = 
        (ADDRESS = (PROTOCOL = TCP)(HOST = {db_hostname}) (PORT = {db_port}))
        (ADDRESS = (PROTOCOL = TCP)(HOST = {db_hostname_alt}) (PORT = {db_port}))
        )(CONNECT_DATA = (SERVICE_NAME = {db_service})))
