# Zugangsdaten Mirakel-Datenbank:
MIRAKEL:
    db_name: mirakel
    db_port: 1521
    db_user: ischotte
    db_pwd: DaWoodyWoodz01!
    db_hostname: dof1c1.dwd.de
    db_hostname_alt: dlu1c1.dwd.de
    db_service: mirakel.dwd.de
    db_arraysize: 1000
    db_connection_string_raw: > 
        (DESCRIPTION =
        (ADDRESS_LIST = 
        (ADDRESS = (PROTOCOL = TCP)(HOST = {db_hostname}) (PORT = {db_port}))
        (ADDRESS = (PROTOCOL = TCP)(HOST = {db_hostname_alt}) (PORT = {db_port}))
        )(CONNECT_DATA = (SERVICE_NAME = {db_service})))
